services:
  stable-diffusion:
    image: ghcr.io/ai-dock/stable-diffusion-webui:latest-cuda
    container_name: stable-diffusion
    profiles: ["gpu-nvidia"]
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - WEB_ENABLE_AUTH=false
      - NVIDIA_VISIBLE_DEVICES=all
      - CLI_ARGS=--xformers --medvram-sdxl --api --listen
    volumes:
      - ../../.services/stable-diffusion/models/:/opt/stable-diffusion-webui/models
      - ../../.services/stable-diffusion/outputs:/opt/stable-diffusion-webui/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
